import type { SeedExercise, SeedWorkout } from '@/lib/program/types'

export const PROGRAM_NAME = 'Гіпертрофія A/B/C'
export const CYCLE_LENGTH_WEEKS = 13

export const SEED_EXERCISES: SeedExercise[] = [
  { key: 'squat', name: 'Присід', muscleGroup: 'legs', weightType: 'barbell' },
  { key: 'bench', name: 'Жим лежачи', muscleGroup: 'chest', weightType: 'barbell' },
  {
    key: 'pull_weighted',
    name: 'Підтягування з вагою',
    muscleGroup: 'back',
    weightType: 'bodyweight_plus',
  },
  {
    key: 'lateral_raise',
    name: 'Махи гантелями в сторони',
    muscleGroup: 'shoulders',
    weightType: 'dumbbell_per_hand',
  },
  { key: 'curl', name: 'Біцепс зі штангою', muscleGroup: 'biceps', weightType: 'barbell' },
  { key: 'rdl', name: 'Румунська тяга', muscleGroup: 'legs', weightType: 'barbell' },
  {
    key: 'incline_db',
    name: 'Жим гантелей на похилій лаві 30–45°',
    muscleGroup: 'chest',
    weightType: 'dumbbell_per_hand',
  },
  {
    key: 'row_cable',
    name: 'Тяга горизонтального блоку сидячи',
    muscleGroup: 'back',
    weightType: 'cable',
  },
  { key: 'ohp', name: 'Жим стоячи', muscleGroup: 'shoulders', weightType: 'barbell' },
  {
    key: 'triceps_oh',
    name: 'Розгинання на трицепс з-за голови на блоці',
    muscleGroup: 'triceps',
    weightType: 'cable',
  },
  {
    key: 'pull_bw',
    name: 'Підтягування з власною вагою',
    muscleGroup: 'back',
    weightType: 'bodyweight_plus',
  },
]

export const SEED_WORKOUTS: SeedWorkout[] = [
  {
    code: 'A',
    slots: [
      {
        exerciseKey: 'squat',
        sets: 3,
        repMin: 6,
        repMax: 10,
        rirMin: 2,
        rirMax: 3,
        restSec: 180,
        startWeight: 70,
        increment: 2.5,
        twelveWeekTargetMin: 85,
        twelveWeekTargetMax: 90,
      },
      {
        exerciseKey: 'bench',
        sets: 4,
        repMin: 6,
        repMax: 10,
        rirMin: 1,
        rirMax: 2,
        restSec: 150,
        startWeight: 65,
        increment: 2.5,
        extraSetInPhase: true,
        twelveWeekTargetMin: 80,
        twelveWeekTargetMax: 82.5,
      },
      {
        exerciseKey: 'pull_weighted',
        sets: 4,
        repMin: 6,
        repMax: 10,
        rirMin: 1,
        rirMax: 2,
        restSec: 150,
        startWeight: 5,
        increment: 2.5,
        extraSetInPhase: true,
        twelveWeekTargetMin: 15,
        twelveWeekTargetMax: 17.5,
      },
      {
        exerciseKey: 'lateral_raise',
        sets: 3,
        repMin: 12,
        repMax: 20,
        rirMin: 1,
        rirMax: 1,
        restSec: 75,
        startWeight: 7,
        increment: 1,
      },
      {
        exerciseKey: 'curl',
        sets: 3,
        repMin: 8,
        repMax: 12,
        rirMin: 1,
        rirMax: 1,
        restSec: 90,
        startWeight: 27.5,
        increment: 2.5,
        twelveWeekTargetMin: 37.5,
        twelveWeekTargetMax: 40,
      },
    ],
  },
  {
    code: 'B',
    slots: [
      {
        exerciseKey: 'rdl',
        sets: 3,
        repMin: 8,
        repMax: 10,
        rirMin: 2,
        rirMax: 3,
        restSec: 150,
        startWeight: 55,
        increment: 2.5,
        twelveWeekTargetMin: 70,
        twelveWeekTargetMax: 75,
      },
      {
        exerciseKey: 'incline_db',
        sets: 4,
        repMin: 8,
        repMax: 12,
        rirMin: 1,
        rirMax: 2,
        restSec: 120,
        startWeight: 23,
        increment: 1,
        extraSetInPhase: true,
      },
      {
        exerciseKey: 'row_cable',
        sets: 4,
        repMin: 8,
        repMax: 12,
        rirMin: 1,
        rirMax: 2,
        restSec: 120,
        startWeight: null,
        increment: 1,
        extraSetInPhase: true,
      },
      {
        exerciseKey: 'ohp',
        sets: 3,
        repMin: 6,
        repMax: 10,
        rirMin: 2,
        rirMax: 2,
        restSec: 120,
        startWeight: 35,
        increment: 2.5,
        twelveWeekTargetMin: 42.5,
        twelveWeekTargetMax: 45,
      },
      {
        exerciseKey: 'triceps_oh',
        sets: 3,
        repMin: 10,
        repMax: 15,
        rirMin: 1,
        rirMax: 1,
        restSec: 90,
        startWeight: null,
        increment: 1,
      },
    ],
  },
  {
    code: 'C',
    slots: [
      {
        exerciseKey: 'bench',
        sets: 3,
        repMin: 8,
        repMax: 12,
        rirMin: 1,
        rirMax: 2,
        restSec: 120,
        startWeight: 60,
        increment: 2.5,
        extraSetInPhase: true,
      },
      {
        exerciseKey: 'pull_bw',
        sets: 3,
        repMin: 8,
        repMax: 12,
        rirMin: 1,
        rirMax: 2,
        restSec: 120,
        startWeight: 0,
        increment: 2.5,
        extraSetInPhase: true,
      },
      {
        exerciseKey: 'row_cable',
        sets: 3,
        repMin: 10,
        repMax: 12,
        rirMin: 1,
        rirMax: 1,
        restSec: 90,
        startWeight: null,
        increment: 1,
      },
      {
        exerciseKey: 'lateral_raise',
        sets: 3,
        repMin: 12,
        repMax: 20,
        rirMin: 1,
        rirMax: 1,
        restSec: 60,
        startWeight: 7,
        increment: 1,
      },
      {
        exerciseKey: 'curl',
        sets: 2,
        repMin: 10,
        repMax: 12,
        rirMin: 1,
        rirMax: 1,
        restSec: 75,
        startWeight: 25,
        increment: 2.5,
      },
      {
        exerciseKey: 'triceps_oh',
        sets: 2,
        repMin: 12,
        repMax: 15,
        rirMin: 1,
        rirMax: 1,
        restSec: 75,
        startWeight: null,
        increment: 1,
      },
    ],
  },
]
